#!/usr/bin/python
"""
Setup script for Intrepyd
"""

import os
import sys
from setuptools import setup, find_packages, Distribution
try:
    from setuptools.command.bdist_wheel import bdist_wheel
except ImportError:     # setuptools older than 70.1
    from wheel.bdist_wheel import bdist_wheel

HERE = os.path.abspath(os.path.dirname(__file__))

with open(os.path.join(HERE, 'VERSION'), encoding='utf-8') as version_file:
    version = version_file.read().strip()

# The intrepid backend is a prebuilt shared library, put next to
# intrepyd/__init__.py by fetch_intrepid.py, which also records the platform
# it is for in .intrepid/PLATFORM. Each wheel carries the library of one
# platform. intrepyd/api.py loads it through ctypes, so the wheel does not
# depend on the python version: its tag is py3-none-<platform>.
LIBRARIES = ['libintrepid.so', 'intrepid.dll']
WHEEL_PLATFORMS = {
    'linux-x86_64': 'manylinux_2_28_x86_64',
    'windows-x86_64': 'win_amd64',
}


def fetched_platform():
    path = os.path.join(HERE, '.intrepid', 'PLATFORM')
    if not os.path.isfile(path):
        return None
    with open(path, encoding='utf-8') as platform_file:
        return platform_file.read().strip()


class BinaryDistribution(Distribution):
    """Has a native library, so the package goes in platlib, not purelib"""

    def has_ext_modules(self):
        return True


class PlatformWheel(bdist_wheel):
    """A wheel tagged for the platform of the bundled library"""

    def run(self):
        bundled = [name for name in LIBRARIES
                   if os.path.isfile(os.path.join(HERE, 'intrepyd', name))]
        if len(bundled) != 1 or fetched_platform() not in WHEEL_PLATFORMS:
            sys.exit('Error: run "make fetch_intrepid" first, to put the intrepid '
                     'library of exactly one platform into intrepyd/')
        super().run()

    def get_tag(self):
        return 'py3', 'none', WHEEL_PLATFORMS[fetched_platform()]


long_desc = """
========
Intrepyd
========
Intrepyd is a python module that provides a simulator and model checkers in form of
a rich API, to allow the rapid prototyping of **formal methods** algorithms
for the rigorous analysis of circuits, specifications, models.

============================
Formal Methods Little Corner
============================
A collection of experiences using Intrepyd can be found `here <https://formalmethods.github.io>`_.

====
FAQs
====
Please refer to the dedicated `Wiki page <https://github.com/formalmethods/intrepyd/wiki/FAQs>`_.
"""

setup(name='intrepyd',
      version=version,
      description='Intrepyd Model Checker',
      author='Roberto Bruttomesso',
      author_email='roberto.bruttomesso@gmail.com',
      maintainer='Roberto Bruttomesso',
      maintainer_email='roberto.bruttomesso@gmail.com',
      url='https://github.com/formalmethods/intrepyd',
      # The antlr runtime pin is deliberate: the checked in lexers and parsers
      # under lustre2py/, formula2py/ and iec611312py/ are generated by ANTLR
      # 4.9.1 and the runtime has to match the generator.
      install_requires=['pandas', 'antlr4-python3-runtime==4.9.1', 'flask', 'gunicorn'],
      python_requires='>=3.9',
      packages=find_packages(exclude=['*.tests', '*.tests.*']),
      # Only the one library that is present ends up in the wheel
      package_data={'intrepyd': LIBRARIES + ['LICENSE.intrepid']},
      cmdclass={'bdist_wheel': PlatformWheel},
      distclass=BinaryDistribution,
      zip_safe=False,
      # intrepyd itself is BSD; the intrepid library bundled in the wheels is
      # proprietary, and may be used freely as part of intrepyd
      license='BSD-3-Clause; bundled intrepid library: see LICENSE.intrepid',
      platforms=['Windows', 'Linux'],
      classifiers=[
          'Development Status :: 4 - Beta',
          'Intended Audience :: Science/Research',
          'License :: OSI Approved :: BSD License',
          'Operating System :: Microsoft :: Windows',
          'Operating System :: POSIX :: Linux',
          'Programming Language :: Python :: 3',
          'Topic :: Scientific/Engineering',
      ],
      long_description=long_desc
)
