Int_ctx ctx0 = mk_ctx();
Int_type type0 = mk_boolean_type(ctx0);
Int_type type1 = mk_int8_type(ctx0);
Int_type type2 = mk_int16_type(ctx0);
Int_type type3 = mk_int32_type(ctx0);
Int_type type4 = mk_int64_type(ctx0);
Int_type type5 = mk_uint8_type(ctx0);
Int_type type6 = mk_uint16_type(ctx0);
Int_type type7 = mk_uint32_type(ctx0);
Int_type type8 = mk_uint64_type(ctx0);
Int_type type9 = mk_real_type(ctx0);
Int_type type10 = mk_float16_type(ctx0);
Int_type type11 = mk_float32_type(ctx0);
Int_type type12 = mk_float64_type(ctx0);
Int_type type13 = mk_int_type(ctx0);
Int_net net4294967295 = mk_undef(ctx0);
Int_net net1 = mk_true(ctx0);
Int_net net2 = mk_false(ctx0);
Int_net net6 = mk_input(ctx0, "clk_input", type0);
Int_net net7 = mk_latch(ctx0, "clk_first", type0);
set_latch_init_next(ctx0, net7, net1, net2);
Int_net net8 = mk_latch(ctx0, "clk_inv", type0);
Int_net net9 = mk_ite(ctx0, net7, net6, net8);
Int_net net10 = mk_not(ctx0, net9);
set_latch_init_next(ctx0, net8, net1, net10);
Int_engine_bmc bmc0 = mk_engine_bmc(ctx0);
set_bmc_current_depth(bmc0, 0);
bmc_add_target(ctx0, bmc0, net10);
bmc_reach_targets(bmc0);
del_ctx(ctx0);
Int_ctx ctx1 = mk_ctx();
Int_type type0 = mk_boolean_type(ctx0);
Int_type type1 = mk_int8_type(ctx0);
Int_type type2 = mk_int16_type(ctx0);
Int_type type3 = mk_int32_type(ctx0);
Int_type type4 = mk_int64_type(ctx0);
Int_type type5 = mk_uint8_type(ctx0);
Int_type type6 = mk_uint16_type(ctx0);
Int_type type7 = mk_uint32_type(ctx0);
Int_type type8 = mk_uint64_type(ctx0);
Int_type type9 = mk_real_type(ctx0);
Int_type type10 = mk_float16_type(ctx0);
Int_type type11 = mk_float32_type(ctx0);
Int_type type12 = mk_float64_type(ctx0);
Int_type type13 = mk_int_type(ctx0);
Int_net net4294967295 = mk_undef(ctx0);
Int_net net1 = mk_true(ctx0);
Int_net net2 = mk_false(ctx0);
Int_net net6 = mk_input(ctx0, "clk_input", type0);
Int_net net7 = mk_latch(ctx0, "clk_first", type0);
set_latch_init_next(ctx0, net7, net1, net2);
Int_net net8 = mk_latch(ctx0, "clk_inv", type0);
Int_net net9 = mk_ite(ctx0, net7, net6, net8);
Int_net net10 = mk_not(ctx0, net9);
set_latch_init_next(ctx0, net8, net1, net10);
Int_engine_bmc bmc0 = mk_engine_bmc(ctx0);
set_bmc_current_depth(bmc0, 0);
bmc_add_target(ctx0, bmc0, net9);
bmc_reach_targets(bmc0);
del_ctx(ctx0);
Int_ctx ctx1 = mk_ctx();
Int_type type0 = mk_boolean_type(ctx0);
Int_type type1 = mk_int8_type(ctx0);
Int_type type2 = mk_int16_type(ctx0);
Int_type type3 = mk_int32_type(ctx0);
Int_type type4 = mk_int64_type(ctx0);
Int_type type5 = mk_uint8_type(ctx0);
Int_type type6 = mk_uint16_type(ctx0);
Int_type type7 = mk_uint32_type(ctx0);
Int_type type8 = mk_uint64_type(ctx0);
Int_type type9 = mk_real_type(ctx0);
Int_type type10 = mk_float16_type(ctx0);
Int_type type11 = mk_float32_type(ctx0);
Int_type type12 = mk_float64_type(ctx0);
Int_type type13 = mk_int_type(ctx0);
Int_net net4294967295 = mk_undef(ctx0);
Int_net net1 = mk_true(ctx0);
Int_net net2 = mk_false(ctx0);
Int_net net6 = mk_input(ctx0, "clk_input", type0);
Int_net net7 = mk_latch(ctx0, "clk_first", type0);
set_latch_init_next(ctx0, net7, net1, net2);
Int_net net8 = mk_latch(ctx0, "clk_inv", type0);
Int_net net9 = mk_ite(ctx0, net7, net6, net8);
Int_net net10 = mk_not(ctx0, net9);
set_latch_init_next(ctx0, net8, net1, net10);
Int_net net11 = mk_number(ctx0, "4", type1);
Int_net net12 = mk_number(ctx0, "0", type1);
Int_net net13 = mk_number(ctx0, "1", type1);
Int_net net14 = mk_latch(ctx0, "counter", type1);
Int_net net17 = mk_lt(ctx0, net14, net11);
Int_net net20 = mk_add(ctx0, net14, net13);
Int_net net22 = mk_ite(ctx0, net17, net20, net14);
set_latch_init_next(ctx0, net14, net12, net22);
Int_net net16 = mk_not(ctx0, net17);
Int_engine_br br0 = mk_engine_br(ctx0);
Int_net net25 = mk_and(ctx0, net16, net10);
br_add_target(ctx0, br0, net25);
br_add_watch(ctx0, br0, net9);
br_reach_targets(br0);
br_last_reached_targets_number(br0);
br_last_reached_target(br0, 0);
Int_trace trace0 = br_get_trace(ctx0, br0, net25);
trace_prepare_value_for_net(ctx0, trace0, net9, 0);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 1);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 2);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 3);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 4);
value_at(0);
del_ctx(ctx0);
Int_ctx ctx1 = mk_ctx();
Int_type type0 = mk_boolean_type(ctx0);
Int_type type1 = mk_int8_type(ctx0);
Int_type type2 = mk_int16_type(ctx0);
Int_type type3 = mk_int32_type(ctx0);
Int_type type4 = mk_int64_type(ctx0);
Int_type type5 = mk_uint8_type(ctx0);
Int_type type6 = mk_uint16_type(ctx0);
Int_type type7 = mk_uint32_type(ctx0);
Int_type type8 = mk_uint64_type(ctx0);
Int_type type9 = mk_real_type(ctx0);
Int_type type10 = mk_float16_type(ctx0);
Int_type type11 = mk_float32_type(ctx0);
Int_type type12 = mk_float64_type(ctx0);
Int_type type13 = mk_int_type(ctx0);
Int_net net4294967295 = mk_undef(ctx0);
Int_net net1 = mk_true(ctx0);
Int_net net2 = mk_false(ctx0);
Int_net net6 = mk_input(ctx0, "clk_input", type0);
Int_net net7 = mk_latch(ctx0, "clk_first", type0);
set_latch_init_next(ctx0, net7, net1, net2);
Int_net net8 = mk_latch(ctx0, "clk_inv", type0);
Int_net net9 = mk_ite(ctx0, net7, net6, net8);
Int_net net10 = mk_not(ctx0, net9);
set_latch_init_next(ctx0, net8, net1, net10);
Int_net net11 = mk_number(ctx0, "4", type1);
Int_net net12 = mk_number(ctx0, "0", type1);
Int_net net13 = mk_number(ctx0, "1", type1);
Int_net net14 = mk_latch(ctx0, "counter", type1);
Int_net net17 = mk_lt(ctx0, net14, net11);
Int_net net20 = mk_add(ctx0, net14, net13);
Int_net net22 = mk_ite(ctx0, net17, net20, net14);
set_latch_init_next(ctx0, net14, net12, net22);
Int_net net16 = mk_not(ctx0, net17);
Int_engine_br br0 = mk_engine_br(ctx0);
Int_net net25 = mk_and(ctx0, net16, net9);
br_add_target(ctx0, br0, net25);
br_add_watch(ctx0, br0, net9);
br_reach_targets(br0);
br_last_reached_targets_number(br0);
br_last_reached_target(br0, 0);
Int_trace trace0 = br_get_trace(ctx0, br0, net25);
trace_prepare_value_for_net(ctx0, trace0, net9, 0);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 1);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 2);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 3);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 4);
value_at(0);
del_ctx(ctx0);
Int_ctx ctx1 = mk_ctx();
Int_type type0 = mk_boolean_type(ctx0);
Int_type type1 = mk_int8_type(ctx0);
Int_type type2 = mk_int16_type(ctx0);
Int_type type3 = mk_int32_type(ctx0);
Int_type type4 = mk_int64_type(ctx0);
Int_type type5 = mk_uint8_type(ctx0);
Int_type type6 = mk_uint16_type(ctx0);
Int_type type7 = mk_uint32_type(ctx0);
Int_type type8 = mk_uint64_type(ctx0);
Int_type type9 = mk_real_type(ctx0);
Int_type type10 = mk_float16_type(ctx0);
Int_type type11 = mk_float32_type(ctx0);
Int_type type12 = mk_float64_type(ctx0);
Int_type type13 = mk_int_type(ctx0);
Int_net net4294967295 = mk_undef(ctx0);
Int_net net1 = mk_true(ctx0);
Int_net net2 = mk_false(ctx0);
Int_net net6 = mk_input(ctx0, "clock_input", type0);
Int_net net7 = mk_latch(ctx0, "clock_first", type0);
set_latch_init_next(ctx0, net7, net1, net2);
Int_net net8 = mk_latch(ctx0, "clock_inv", type0);
Int_net net9 = mk_ite(ctx0, net7, net6, net8);
Int_net net10 = mk_not(ctx0, net9);
set_latch_init_next(ctx0, net8, net1, net10);
Int_simulator sim0 = mk_simulator(ctx0);
Int_trace trace0 = mk_trace(ctx0);
trace_set_value(ctx0, trace0, net6, 0, "F");
simulator_add_watch(ctx0, sim0, net9);
simulator_add_watch(ctx0, sim0, net6);
simulator_simulate(sim0, trace0, 10);
trace_prepare_value_for_net(ctx0, trace0, net6, 0);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 0);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 1);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 2);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 3);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 4);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 5);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 6);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 7);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 8);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 9);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 10);
value_at(0);
del_ctx(ctx0);
Int_ctx ctx1 = mk_ctx();
Int_type type0 = mk_boolean_type(ctx0);
Int_type type1 = mk_int8_type(ctx0);
Int_type type2 = mk_int16_type(ctx0);
Int_type type3 = mk_int32_type(ctx0);
Int_type type4 = mk_int64_type(ctx0);
Int_type type5 = mk_uint8_type(ctx0);
Int_type type6 = mk_uint16_type(ctx0);
Int_type type7 = mk_uint32_type(ctx0);
Int_type type8 = mk_uint64_type(ctx0);
Int_type type9 = mk_real_type(ctx0);
Int_type type10 = mk_float16_type(ctx0);
Int_type type11 = mk_float32_type(ctx0);
Int_type type12 = mk_float64_type(ctx0);
Int_type type13 = mk_int_type(ctx0);
Int_net net4294967295 = mk_undef(ctx0);
Int_net net1 = mk_true(ctx0);
Int_net net2 = mk_false(ctx0);
Int_net net6 = mk_number(ctx0, "10", type1);
Int_net net7 = mk_number(ctx0, "0", type1);
Int_net net8 = mk_number(ctx0, "1", type1);
Int_net net9 = mk_latch(ctx0, "counter", type1);
Int_net net12 = mk_lt(ctx0, net9, net6);
Int_net net15 = mk_add(ctx0, net9, net8);
Int_net net17 = mk_ite(ctx0, net12, net15, net9);
set_latch_init_next(ctx0, net9, net7, net17);
Int_net net11 = mk_not(ctx0, net12);
Int_simulator sim0 = mk_simulator(ctx0);
Int_trace trace0 = mk_trace(ctx0);
simulator_add_watch(ctx0, sim0, net9);
simulator_add_watch(ctx0, sim0, net11);
simulator_simulate(sim0, trace0, 12);
trace_prepare_value_for_net(ctx0, trace0, net9, 9);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net11, 9);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 10);
value_at(0);
value_at(1);
trace_prepare_value_for_net(ctx0, trace0, net11, 10);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 11);
value_at(0);
value_at(1);
trace_prepare_value_for_net(ctx0, trace0, net11, 11);
value_at(0);
del_ctx(ctx0);
Int_ctx ctx1 = mk_ctx();
Int_type type0 = mk_boolean_type(ctx0);
Int_type type1 = mk_int8_type(ctx0);
Int_type type2 = mk_int16_type(ctx0);
Int_type type3 = mk_int32_type(ctx0);
Int_type type4 = mk_int64_type(ctx0);
Int_type type5 = mk_uint8_type(ctx0);
Int_type type6 = mk_uint16_type(ctx0);
Int_type type7 = mk_uint32_type(ctx0);
Int_type type8 = mk_uint64_type(ctx0);
Int_type type9 = mk_real_type(ctx0);
Int_type type10 = mk_float16_type(ctx0);
Int_type type11 = mk_float32_type(ctx0);
Int_type type12 = mk_float64_type(ctx0);
Int_type type13 = mk_int_type(ctx0);
Int_net net4294967295 = mk_undef(ctx0);
Int_net net1 = mk_true(ctx0);
Int_net net2 = mk_false(ctx0);
Int_net net6 = mk_latch(ctx0, "delay_back", type0);
Int_net net7 = mk_latch(ctx0, "delay", type0);
set_latch_init_next(ctx0, net6, net2, net1);
set_latch_init_next(ctx0, net7, net2, net6);
Int_engine_bmc bmc0 = mk_engine_bmc(ctx0);
bmc_add_target(ctx0, bmc0, net7);
set_bmc_current_depth(bmc0, 0);
bmc_reach_targets(bmc0);
set_bmc_current_depth(bmc0, 1);
bmc_reach_targets(bmc0);
set_bmc_current_depth(bmc0, 2);
bmc_reach_targets(bmc0);
del_ctx(ctx0);
Int_ctx ctx1 = mk_ctx();
Int_type type0 = mk_boolean_type(ctx0);
Int_type type1 = mk_int8_type(ctx0);
Int_type type2 = mk_int16_type(ctx0);
Int_type type3 = mk_int32_type(ctx0);
Int_type type4 = mk_int64_type(ctx0);
Int_type type5 = mk_uint8_type(ctx0);
Int_type type6 = mk_uint16_type(ctx0);
Int_type type7 = mk_uint32_type(ctx0);
Int_type type8 = mk_uint64_type(ctx0);
Int_type type9 = mk_real_type(ctx0);
Int_type type10 = mk_float16_type(ctx0);
Int_type type11 = mk_float32_type(ctx0);
Int_type type12 = mk_float64_type(ctx0);
Int_type type13 = mk_int_type(ctx0);
Int_net net4294967295 = mk_undef(ctx0);
Int_net net1 = mk_true(ctx0);
Int_net net2 = mk_false(ctx0);
Int_net net6 = mk_input(ctx0, "i", type0);
Int_net net7 = mk_input(ctx0, "clk", type0);
Int_net net8 = mk_latch(ctx0, "ffd_master", type0);
Int_net net9 = mk_latch(ctx0, "ffd_slave", type0);
Int_net net10 = mk_ite(ctx0, net7, net8, net9);
Int_net net11 = mk_not(ctx0, net7);
Int_net net13 = mk_ite(ctx0, net11, net6, net8);
set_latch_init_next(ctx0, net8, net1, net13);
set_latch_init_next(ctx0, net9, net1, net10);
Int_trace trace0 = mk_trace(ctx0);
trace_set_value(ctx0, trace0, net6, 0, "F");
trace_set_value(ctx0, trace0, net6, 1, "T");
trace_set_value(ctx0, trace0, net6, 2, "T");
trace_set_value(ctx0, trace0, net6, 3, "T");
trace_set_value(ctx0, trace0, net6, 4, "F");
trace_set_value(ctx0, trace0, net6, 5, "F");
trace_set_value(ctx0, trace0, net7, 0, "F");
trace_set_value(ctx0, trace0, net7, 1, "T");
trace_set_value(ctx0, trace0, net7, 2, "F");
trace_set_value(ctx0, trace0, net7, 3, "T");
trace_set_value(ctx0, trace0, net7, 4, "F");
trace_set_value(ctx0, trace0, net7, 5, "T");
Int_simulator sim0 = mk_simulator(ctx0);
simulator_add_watch(ctx0, sim0, net10);
simulator_simulate(sim0, trace0, 6);
trace_prepare_value_for_net(ctx0, trace0, net10, 0);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net10, 1);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net10, 2);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net10, 3);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net10, 4);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net10, 5);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net10, 6);
value_at(0);
del_ctx(ctx0);
Int_ctx ctx1 = mk_ctx();
Int_type type0 = mk_boolean_type(ctx0);
Int_type type1 = mk_int8_type(ctx0);
Int_type type2 = mk_int16_type(ctx0);
Int_type type3 = mk_int32_type(ctx0);
Int_type type4 = mk_int64_type(ctx0);
Int_type type5 = mk_uint8_type(ctx0);
Int_type type6 = mk_uint16_type(ctx0);
Int_type type7 = mk_uint32_type(ctx0);
Int_type type8 = mk_uint64_type(ctx0);
Int_type type9 = mk_real_type(ctx0);
Int_type type10 = mk_float16_type(ctx0);
Int_type type11 = mk_float32_type(ctx0);
Int_type type12 = mk_float64_type(ctx0);
Int_type type13 = mk_int_type(ctx0);
Int_net net4294967295 = mk_undef(ctx0);
Int_net net1 = mk_true(ctx0);
Int_net net2 = mk_false(ctx0);
Int_net net6 = mk_input(ctx0, "i", type0);
Int_net net7 = mk_input(ctx0, "clk", type0);
Int_net net8 = mk_latch(ctx0, "ffd_master", type0);
Int_net net9 = mk_latch(ctx0, "ffd_slave", type0);
Int_net net10 = mk_ite(ctx0, net7, net8, net9);
Int_net net11 = mk_not(ctx0, net7);
Int_net net13 = mk_ite(ctx0, net11, net6, net8);
set_latch_init_next(ctx0, net8, net1, net13);
set_latch_init_next(ctx0, net9, net1, net10);
Int_trace trace0 = mk_trace(ctx0);
trace_set_value(ctx0, trace0, net6, 0, "F");
trace_set_value(ctx0, trace0, net6, 1, "F");
trace_set_value(ctx0, trace0, net6, 2, "T");
trace_set_value(ctx0, trace0, net6, 3, "F");
trace_set_value(ctx0, trace0, net6, 4, "F");
trace_set_value(ctx0, trace0, net6, 5, "T");
trace_set_value(ctx0, trace0, net7, 0, "F");
trace_set_value(ctx0, trace0, net7, 1, "T");
trace_set_value(ctx0, trace0, net7, 2, "F");
trace_set_value(ctx0, trace0, net7, 3, "T");
trace_set_value(ctx0, trace0, net7, 4, "F");
trace_set_value(ctx0, trace0, net7, 5, "T");
Int_simulator sim0 = mk_simulator(ctx0);
simulator_add_watch(ctx0, sim0, net10);
simulator_simulate(sim0, trace0, 6);
trace_prepare_value_for_net(ctx0, trace0, net10, 0);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net10, 1);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net10, 2);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net10, 3);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net10, 4);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net10, 5);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net10, 6);
value_at(0);
del_ctx(ctx0);
Int_ctx ctx1 = mk_ctx();
Int_type type0 = mk_boolean_type(ctx0);
Int_type type1 = mk_int8_type(ctx0);
Int_type type2 = mk_int16_type(ctx0);
Int_type type3 = mk_int32_type(ctx0);
Int_type type4 = mk_int64_type(ctx0);
Int_type type5 = mk_uint8_type(ctx0);
Int_type type6 = mk_uint16_type(ctx0);
Int_type type7 = mk_uint32_type(ctx0);
Int_type type8 = mk_uint64_type(ctx0);
Int_type type9 = mk_real_type(ctx0);
Int_type type10 = mk_float16_type(ctx0);
Int_type type11 = mk_float32_type(ctx0);
Int_type type12 = mk_float64_type(ctx0);
Int_type type13 = mk_int_type(ctx0);
Int_net net4294967295 = mk_undef(ctx0);
Int_net net1 = mk_true(ctx0);
Int_net net2 = mk_false(ctx0);
Int_net net6 = mk_input(ctx0, "i", type0);
Int_net net7 = mk_input(ctx0, "e", type0);
Int_net net8 = mk_input(ctx0, "clk", type0);
Int_net net9 = mk_latch(ctx0, "ffd_master", type0);
Int_net net10 = mk_latch(ctx0, "ffd_slave", type0);
Int_net net11 = mk_ite(ctx0, net8, net9, net10);
Int_net net12 = mk_ite(ctx0, net7, net6, net11);
Int_net net13 = mk_not(ctx0, net8);
Int_net net15 = mk_ite(ctx0, net13, net12, net9);
set_latch_init_next(ctx0, net9, net1, net15);
set_latch_init_next(ctx0, net10, net1, net11);
Int_trace trace0 = mk_trace(ctx0);
trace_set_value(ctx0, trace0, net6, 0, "F");
trace_set_value(ctx0, trace0, net6, 1, "F");
trace_set_value(ctx0, trace0, net6, 2, "T");
trace_set_value(ctx0, trace0, net6, 3, "F");
trace_set_value(ctx0, trace0, net6, 4, "T");
trace_set_value(ctx0, trace0, net6, 5, "T");
trace_set_value(ctx0, trace0, net7, 0, "T");
trace_set_value(ctx0, trace0, net7, 1, "T");
trace_set_value(ctx0, trace0, net7, 2, "F");
trace_set_value(ctx0, trace0, net7, 3, "F");
trace_set_value(ctx0, trace0, net7, 4, "T");
trace_set_value(ctx0, trace0, net7, 5, "T");
trace_set_value(ctx0, trace0, net8, 0, "F");
trace_set_value(ctx0, trace0, net8, 1, "T");
trace_set_value(ctx0, trace0, net8, 2, "F");
trace_set_value(ctx0, trace0, net8, 3, "T");
trace_set_value(ctx0, trace0, net8, 4, "F");
trace_set_value(ctx0, trace0, net8, 5, "T");
Int_simulator sim0 = mk_simulator(ctx0);
simulator_add_watch(ctx0, sim0, net11);
simulator_simulate(sim0, trace0, 6);
trace_prepare_value_for_net(ctx0, trace0, net11, 0);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net11, 1);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net11, 2);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net11, 3);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net11, 4);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net11, 5);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net11, 6);
value_at(0);
del_ctx(ctx0);
Int_ctx ctx1 = mk_ctx();
Int_type type0 = mk_boolean_type(ctx0);
Int_type type1 = mk_int8_type(ctx0);
Int_type type2 = mk_int16_type(ctx0);
Int_type type3 = mk_int32_type(ctx0);
Int_type type4 = mk_int64_type(ctx0);
Int_type type5 = mk_uint8_type(ctx0);
Int_type type6 = mk_uint16_type(ctx0);
Int_type type7 = mk_uint32_type(ctx0);
Int_type type8 = mk_uint64_type(ctx0);
Int_type type9 = mk_real_type(ctx0);
Int_type type10 = mk_float16_type(ctx0);
Int_type type11 = mk_float32_type(ctx0);
Int_type type12 = mk_float64_type(ctx0);
Int_type type13 = mk_int_type(ctx0);
Int_net net4294967295 = mk_undef(ctx0);
Int_net net1 = mk_true(ctx0);
Int_net net2 = mk_false(ctx0);
Int_net net6 = mk_input(ctx0, "i", type0);
Int_net net7 = mk_input(ctx0, "e", type0);
Int_net net8 = mk_input(ctx0, "clk", type0);
Int_net net9 = mk_latch(ctx0, "ffd_master", type0);
Int_net net10 = mk_latch(ctx0, "ffd_slave", type0);
Int_net net11 = mk_ite(ctx0, net8, net9, net10);
Int_net net12 = mk_ite(ctx0, net7, net6, net11);
Int_net net13 = mk_not(ctx0, net8);
Int_net net15 = mk_ite(ctx0, net13, net12, net9);
set_latch_init_next(ctx0, net9, net1, net15);
set_latch_init_next(ctx0, net10, net1, net11);
Int_trace trace0 = mk_trace(ctx0);
trace_set_value(ctx0, trace0, net6, 0, "T");
trace_set_value(ctx0, trace0, net6, 1, "F");
trace_set_value(ctx0, trace0, net6, 2, "F");
trace_set_value(ctx0, trace0, net7, 0, "T");
trace_set_value(ctx0, trace0, net7, 1, "T");
trace_set_value(ctx0, trace0, net7, 2, "F");
trace_set_value(ctx0, trace0, net8, 0, "F");
trace_set_value(ctx0, trace0, net8, 1, "T");
trace_set_value(ctx0, trace0, net8, 2, "F");
trace_set_value(ctx0, trace0, net8, 3, "T");
Int_simulator sim0 = mk_simulator(ctx0);
simulator_add_watch(ctx0, sim0, net11);
simulator_simulate(sim0, trace0, 6);
trace_prepare_value_for_net(ctx0, trace0, net11, 0);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net11, 1);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net11, 2);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net11, 3);
value_at(0);
del_ctx(ctx0);
Int_ctx ctx1 = mk_ctx();
Int_type type0 = mk_boolean_type(ctx0);
Int_type type1 = mk_int8_type(ctx0);
Int_type type2 = mk_int16_type(ctx0);
Int_type type3 = mk_int32_type(ctx0);
Int_type type4 = mk_int64_type(ctx0);
Int_type type5 = mk_uint8_type(ctx0);
Int_type type6 = mk_uint16_type(ctx0);
Int_type type7 = mk_uint32_type(ctx0);
Int_type type8 = mk_uint64_type(ctx0);
Int_type type9 = mk_real_type(ctx0);
Int_type type10 = mk_float16_type(ctx0);
Int_type type11 = mk_float32_type(ctx0);
Int_type type12 = mk_float64_type(ctx0);
Int_type type13 = mk_int_type(ctx0);
Int_net net4294967295 = mk_undef(ctx0);
Int_net net1 = mk_true(ctx0);
Int_net net2 = mk_false(ctx0);
Int_net net6 = mk_input(ctx0, "i", type0);
Int_net net7 = mk_input(ctx0, "e", type0);
Int_net net8 = mk_latch(ctx0, "l", type0);
Int_net net9 = mk_ite(ctx0, net7, net6, net8);
set_latch_init_next(ctx0, net8, net1, net9);
Int_trace trace0 = mk_trace(ctx0);
trace_set_value(ctx0, trace0, net6, 0, "T");
trace_set_value(ctx0, trace0, net6, 1, "F");
trace_set_value(ctx0, trace0, net6, 2, "F");
trace_set_value(ctx0, trace0, net7, 0, "T");
trace_set_value(ctx0, trace0, net7, 1, "F");
trace_set_value(ctx0, trace0, net7, 2, "T");
Int_simulator sim0 = mk_simulator(ctx0);
simulator_add_watch(ctx0, sim0, net8);
simulator_simulate(sim0, trace0, 3);
trace_prepare_value_for_net(ctx0, trace0, net8, 0);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net8, 1);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net8, 2);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net8, 3);
value_at(0);
del_ctx(ctx0);
Int_ctx ctx1 = mk_ctx();
Int_type type0 = mk_boolean_type(ctx0);
Int_type type1 = mk_int8_type(ctx0);
Int_type type2 = mk_int16_type(ctx0);
Int_type type3 = mk_int32_type(ctx0);
Int_type type4 = mk_int64_type(ctx0);
Int_type type5 = mk_uint8_type(ctx0);
Int_type type6 = mk_uint16_type(ctx0);
Int_type type7 = mk_uint32_type(ctx0);
Int_type type8 = mk_uint64_type(ctx0);
Int_type type9 = mk_real_type(ctx0);
Int_type type10 = mk_float16_type(ctx0);
Int_type type11 = mk_float32_type(ctx0);
Int_type type12 = mk_float64_type(ctx0);
Int_type type13 = mk_int_type(ctx0);
Int_net net4294967295 = mk_undef(ctx0);
Int_net net1 = mk_true(ctx0);
Int_net net2 = mk_false(ctx0);
Int_net net6 = mk_input(ctx0, "i", type0);
Int_net net7 = mk_latch(ctx0, "l", type0);
set_latch_init_next(ctx0, net7, net1, net6);
Int_trace trace0 = mk_trace(ctx0);
trace_set_value(ctx0, trace0, net6, 0, "T");
trace_set_value(ctx0, trace0, net6, 1, "F");
trace_set_value(ctx0, trace0, net6, 2, "T");
Int_simulator sim0 = mk_simulator(ctx0);
simulator_add_watch(ctx0, sim0, net7);
simulator_simulate(sim0, trace0, 3);
trace_prepare_value_for_net(ctx0, trace0, net7, 0);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net7, 1);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net7, 2);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net7, 3);
value_at(0);
del_ctx(ctx0);
Int_ctx ctx1 = mk_ctx();
Int_type type0 = mk_boolean_type(ctx0);
Int_type type1 = mk_int8_type(ctx0);
Int_type type2 = mk_int16_type(ctx0);
Int_type type3 = mk_int32_type(ctx0);
Int_type type4 = mk_int64_type(ctx0);
Int_type type5 = mk_uint8_type(ctx0);
Int_type type6 = mk_uint16_type(ctx0);
Int_type type7 = mk_uint32_type(ctx0);
Int_type type8 = mk_uint64_type(ctx0);
Int_type type9 = mk_real_type(ctx0);
Int_type type10 = mk_float16_type(ctx0);
Int_type type11 = mk_float32_type(ctx0);
Int_type type12 = mk_float64_type(ctx0);
Int_type type13 = mk_int_type(ctx0);
Int_net net4294967295 = mk_undef(ctx0);
Int_net net1 = mk_true(ctx0);
Int_net net2 = mk_false(ctx0);
Int_net net6 = mk_input(ctx0, "sel", type0);
Int_net net7 = mk_input(ctx0, "in0", type0);
Int_net net8 = mk_input(ctx0, "in1", type0);
Int_net net9 = mk_ite(ctx0, net6, net8, net7);
Int_trace trace0 = mk_trace(ctx0);
trace_set_value(ctx0, trace0, net6, 0, "F");
trace_set_value(ctx0, trace0, net7, 0, "T");
trace_set_value(ctx0, trace0, net8, 0, "F");
trace_set_value(ctx0, trace0, net6, 1, "T");
trace_set_value(ctx0, trace0, net7, 1, "T");
trace_set_value(ctx0, trace0, net8, 1, "F");
trace_set_value(ctx0, trace0, net6, 2, "F");
trace_set_value(ctx0, trace0, net7, 2, "F");
trace_set_value(ctx0, trace0, net8, 2, "T");
trace_set_value(ctx0, trace0, net6, 3, "T");
trace_set_value(ctx0, trace0, net7, 3, "F");
trace_set_value(ctx0, trace0, net8, 3, "T");
Int_simulator sim0 = mk_simulator(ctx0);
simulator_add_watch(ctx0, sim0, net9);
simulator_simulate(sim0, trace0, 3);
trace_prepare_value_for_net(ctx0, trace0, net9, 0);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 1);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 2);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 3);
value_at(0);
del_ctx(ctx0);
Int_ctx ctx1 = mk_ctx();
Int_type type0 = mk_boolean_type(ctx0);
Int_type type1 = mk_int8_type(ctx0);
Int_type type2 = mk_int16_type(ctx0);
Int_type type3 = mk_int32_type(ctx0);
Int_type type4 = mk_int64_type(ctx0);
Int_type type5 = mk_uint8_type(ctx0);
Int_type type6 = mk_uint16_type(ctx0);
Int_type type7 = mk_uint32_type(ctx0);
Int_type type8 = mk_uint64_type(ctx0);
Int_type type9 = mk_real_type(ctx0);
Int_type type10 = mk_float16_type(ctx0);
Int_type type11 = mk_float32_type(ctx0);
Int_type type12 = mk_float64_type(ctx0);
Int_type type13 = mk_int_type(ctx0);
Int_net net4294967295 = mk_undef(ctx0);
Int_net net1 = mk_true(ctx0);
Int_net net2 = mk_false(ctx0);
Int_net net6 = mk_input(ctx0, "d", type0);
Int_net net7 = mk_latch(ctx0, "sr_0", type0);
Int_net net8 = mk_latch(ctx0, "sr_1", type0);
Int_net net9 = mk_latch(ctx0, "sr_2", type0);
set_latch_init_next(ctx0, net7, net2, net6);
set_latch_init_next(ctx0, net8, net2, net7);
set_latch_init_next(ctx0, net9, net2, net8);
Int_trace trace0 = mk_trace(ctx0);
trace_set_value(ctx0, trace0, net6, 0, "T");
trace_set_value(ctx0, trace0, net6, 1, "F");
trace_set_value(ctx0, trace0, net6, 2, "T");
trace_set_value(ctx0, trace0, net6, 3, "F");
trace_set_value(ctx0, trace0, net6, 4, "F");
trace_set_value(ctx0, trace0, net6, 5, "T");
Int_simulator sim0 = mk_simulator(ctx0);
simulator_add_watch(ctx0, sim0, net9);
simulator_simulate(sim0, trace0, 6);
trace_prepare_value_for_net(ctx0, trace0, net9, 0);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 1);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 2);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 3);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 4);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 5);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 6);
value_at(0);
trace_prepare_value_for_net(ctx0, trace0, net9, 7);
